SERVER_NAME: "Survival"

TRANSACTIONS:
  MAX_ENTRIES_PER_PAGE: 45
  MAX_PER_PLAYER: 100
  LIMIT_BEHAVIOR: DELETE_OLDEST # Options: DELETE_OLDEST, STOP_RECORDING
  PURGE_AFTER_DAYS: 0

FORMATTING:
  DATE_FORMAT: "dd/MM/yyyy hh:mm:ss a"
  ECONOMY_FORMAT: "#,##0.00"